-- ---------------------------------------------------------------------------
-- Muse v2 live smoke test — paste into the Lovable SQL editor AFTER applying
-- supabase/migrations/20260927120000_muse_mission_board.sql.
--
-- It drives one improvement through the whole protocol and then ABORTS ITSELF,
-- so nothing it creates survives. The expected outcome is an ERROR whose
-- message starts with:
--
--     MUSE_BOARD_SMOKE_OK
--
-- Any other error means the live database behaves differently from the
-- validated harness — report it verbatim; do not edit this file to make it pass.
-- ---------------------------------------------------------------------------
DO $$
DECLARE
  iid uuid;
  tid uuid;
  vid uuid;
  st text;
  vs text;
  n int;
  refused boolean;
BEGIN
  INSERT INTO public.muse_improvements
    (domain_key, problem, intervention, metric, metric_key, created_by, risk, reversibility,
     confidence, recommended_executor, definition_of_done, measurement_window_days, verification_requirement)
  VALUES ('ai_technical_systems', '__smoke problem', '__smoke intervention', '__smoke metric',
          '__smoke.metric', 'muse', 'LOW', 'REVERSIBLE', 'HIGH', 'claude-code', '["smoke"]', 7, 'SYSTEM_VERIFIED')
  RETURNING id INTO iid;

  PERFORM public.muse_transition_improvement(iid, 'SELECTED', 'muse');

  INSERT INTO public.muse_improvement_tasks (improvement_id, title, executor, assigned_by)
  VALUES (iid, '__smoke task', 'claude-code', 'grok-bot') RETURNING id INTO tid;
  SELECT status INTO st FROM public.muse_improvements WHERE id = iid;
  IF st <> 'IN_EXECUTION' THEN RAISE EXCEPTION 'MUSE_BOARD_SMOKE_FAIL: assignment did not advance the improvement (%)', st; END IF;

  PERFORM public.muse_transition_task(tid, 'IN_PROGRESS', 'claude-code');
  PERFORM public.muse_transition_task(tid, 'IMPLEMENTED', 'claude-code', p_claimed_completion => '__smoke claim');
  SELECT verification_id INTO vid FROM public.muse_improvement_tasks WHERE id = tid;
  IF vid IS NULL THEN RAISE EXCEPTION 'MUSE_BOARD_SMOKE_FAIL: IMPLEMENTED did not open a verification'; END IF;

  -- The executor must not be able to verify itself.
  refused := false;
  BEGIN
    PERFORM public.muse_verify(vid, 'claude-code', 'SYSTEM_VERIFIED', p_system_evidence => 'self');
  EXCEPTION WHEN insufficient_privilege THEN refused := true;
  END;
  IF NOT refused THEN RAISE EXCEPTION 'MUSE_BOARD_SMOKE_FAIL: executor verified its own claim'; END IF;

  PERFORM public.muse_verify(vid, 'grok-bot', 'SYSTEM_VERIFIED', p_system_evidence => '__smoke evidence');
  SELECT state INTO st FROM public.muse_improvement_tasks WHERE id = tid;
  SELECT status INTO vs FROM public.muse_improvements WHERE id = iid;
  IF st <> 'COMPLETE' THEN RAISE EXCEPTION 'MUSE_BOARD_SMOKE_FAIL: verified task not COMPLETE (%)', st; END IF;
  IF vs <> 'VERIFICATION' THEN RAISE EXCEPTION 'MUSE_BOARD_SMOKE_FAIL: improvement not in VERIFICATION (%)', vs; END IF;

  PERFORM public.muse_transition_improvement(iid, 'MEASURING', 'grok-bot');

  SELECT count(*) INTO n FROM public.muse_state_events WHERE subject_id IN (iid, tid, vid);
  IF n < 10 THEN RAISE EXCEPTION 'MUSE_BOARD_SMOKE_FAIL: expected >= 10 history events, got %', n; END IF;

  SELECT count(*) INTO n FROM public.muse_agent_queue WHERE id = tid AND executor = 'claude-code';
  IF n <> 1 THEN RAISE EXCEPTION 'MUSE_BOARD_SMOKE_FAIL: task missing from muse_agent_queue'; END IF;
  SELECT count(*) INTO n FROM public.muse_verification_queue WHERE id = vid AND queue_state = 'PASSED';
  IF n <> 1 THEN RAISE EXCEPTION 'MUSE_BOARD_SMOKE_FAIL: verification not PASSED in muse_verification_queue'; END IF;
  SELECT count(*) INTO n FROM public.muse_impact_ledger WHERE id = iid;
  IF n <> 1 THEN RAISE EXCEPTION 'MUSE_BOARD_SMOKE_FAIL: improvement missing from muse_impact_ledger'; END IF;

  -- Abort on purpose: roll back every row this test wrote.
  RAISE EXCEPTION 'MUSE_BOARD_SMOKE_OK — full protocol ran (propose, select, assign, claim, self-verify refused, verify, complete, measure; % history events). Rolled back; nothing was kept.',
    (SELECT count(*) FROM public.muse_state_events WHERE subject_id IN (iid, tid, vid));
END $$;
