/**
 * Row shapes for the Muse read views.
 *
 * Hand-written on purpose: `src/integrations/supabase/types.ts` is generated by
 * Lovable and would drop these on its next regeneration. Keep this file in sync
 * with supabase/migrations/20260925120000_muse_executive_layer.sql.
 */

export type MuseDataStatus =
  | "KNOWN"
  | "AVAILABLE_NOT_CONNECTED"
  | "SOURCE_EXISTS_ACCESS_NEEDED"
  | "NOT_MEASURED"
  | "UNKNOWN"
  | "NEEDS_VERIFICATION";

export type MuseClassification =
  | "FENDI_DECISION"
  | "MUSE_ANALYSIS"
  | "DELEGATE_TO_AGENT"
  | "AUTOMATED_SYSTEM"
  | "HUMAN_OWNER"
  | "WAITING";

export type MuseVerificationState =
  | "CLAIMED"
  | "ARTIFACT_VERIFIED"
  | "SYSTEM_VERIFIED"
  | "LIVE_VERIFIED";

export type MuseSystemStatus =
  | "HEALTHY"
  | "FAILING"
  | "STALE"
  | "NEVER_RAN"
  | "NOT_OBSERVED"
  | "DISABLED"
  | "UNKNOWN";

export type MuseBriefSection =
  | "priorities"
  | "decisions_required"
  | "blockers"
  | "waiting"
  | "financial"
  | "system_failures"
  | "opportunities"
  | "commitments";

export interface MuseBriefRow {
  section: MuseBriefSection;
  rank: number;
  item_type: "open_loop" | "decision" | "system";
  item_id: string;
  title: string;
  domain_key: string;
  domain_name: string;
  detail: string | null;
  classification: MuseClassification;
  owner: string | null;
  due_at: string | null;
  source: string | null;
  source_ref: string | null;
  data_status: MuseDataStatus;
  verification_state: MuseVerificationState;
  as_of: string;
}

export interface MusePortfolioRow {
  domain_key: string;
  name: string;
  owner: string;
  status: string;
  systems: string[] | null;
  source_of_truth: string | null;
  current_bottleneck: string | null;
  current_initiative: string | null;
  next_review_at: string | null;
  data_status: MuseDataStatus;
  notes: string | null;
  sort_order: number;
  open_loops: number;
  blocked_loops: number;
  decisions_pending: number;
  open_conflicts: number;
  active_improvements: number;
  unhealthy_systems: number;
  primary_kpi_name: string | null;
  primary_kpi_value: number | null;
  primary_kpi_unit: string | null;
  primary_kpi_status: MuseDataStatus | null;
  primary_kpi_at: string | null;
  sources_last_verified_at: string | null;
  as_of: string;
}

export interface MuseOpenLoopRow {
  id: string;
  domain_key: string;
  domain_name: string;
  title: string;
  owner: string | null;
  classification: MuseClassification;
  category: string;
  priority: "P0" | "P1" | "P2" | "P3";
  dependency: string | null;
  source: string;
  source_ref: string | null;
  last_evidence_at: string | null;
  next_action: string | null;
  review_at: string | null;
  resolved_at: string | null;
  verification_state: MuseVerificationState;
  notes: string | null;
  state: "OPEN" | "IN_PROGRESS" | "WAITING" | "BLOCKED" | "RESOLVED" | "CANCELLED";
  stored_state: string;
  derive_resolution_from: string | null;
  derived_system_status: MuseSystemStatus | null;
  evidence_stale: boolean;
  review_overdue: boolean;
  data_status: MuseDataStatus;
  as_of: string;
}

export interface MuseDecisionRow {
  id: string;
  domain_key: string;
  domain_name: string;
  question: string;
  context: string | null;
  evidence: string[] | null;
  options: Array<{ option?: string; pro?: string; con?: string }> | null;
  owner: string;
  classification: MuseClassification;
  status: string;
  decision_required_by: string | null;
  review_at: string | null;
  source: string;
  source_ref: string | null;
  overdue: boolean;
  days_remaining: number | null;
  created_at: string;
  as_of: string;
}

export interface MuseSystemHealthRow {
  system_key: string;
  name: string;
  role: string;
  domain_key: string | null;
  expected_cadence: string;
  cadence_minutes: number | null;
  classification: MuseClassification;
  last_success_at: string | null;
  last_failure_at: string | null;
  last_failure_detail: string | null;
  latest_activity_at: string | null;
  pending_count: number;
  failing_count: number;
  waits_on_human: boolean;
  status: MuseSystemStatus;
  data_status: MuseDataStatus;
  blocker: string | null;
  downstream_impact: string | null;
  probe_key: string | null;
  notes: string | null;
  sort_order: number;
  as_of: string;
}

export interface MuseSourceAuthorityRow {
  id: string;
  domain_key: string;
  domain_name: string;
  subject: string;
  authoritative_system: string;
  secondary_system: string | null;
  access_status: MuseDataStatus;
  freshness_target_minutes: number | null;
  last_verified_at: string | null;
  confidence: "HIGH" | "MEDIUM" | "LOW";
  known_conflict: boolean;
  reference: string | null;
  notes: string | null;
  minutes_since_verified: number | null;
  freshness: "FRESH" | "STALE" | "NEVER_VERIFIED" | "NO_TARGET";
  human_verification_required: boolean;
  open_conflicts: number;
  as_of: string;
}

export interface MuseConflictRow {
  id: string;
  domain_key: string;
  domain_name: string;
  subject: string;
  system_a: string;
  value_a: string;
  reference_a: string | null;
  system_b: string;
  value_b: string;
  reference_b: string | null;
  candidate_authority: string | null;
  status: string;
  detected_at: string;
  resolution_notes: string | null;
  as_of: string;
}

export interface MuseImprovementRow {
  id: string;
  domain_key: string;
  domain_name: string;
  baseline: string | null;
  problem: string;
  intervention: string;
  metric: string;
  expected_result: string | null;
  actual_result: string | null;
  owner: string;
  started_at: string | null;
  review_at: string | null;
  verdict: "PENDING" | "KEEP" | "REVISE" | "REVERSE";
  status: "PROPOSED" | "RUNNING" | "MEASURED" | "CLOSED";
  verification_state: MuseVerificationState;
  source_ref: string | null;
  notes: string | null;
  review_due: boolean;
  awaiting_measurement: boolean;
  data_status: MuseDataStatus;
  created_at: string;
  as_of: string;
}

export interface MuseKpiRow {
  metric_key: string;
  domain_key: string;
  domain_name: string;
  name: string;
  unit: string;
  direction: "UP_IS_GOOD" | "DOWN_IS_GOOD" | "NEUTRAL";
  source_system: string;
  target: string | null;
  is_primary: boolean;
  value: number | null;
  data_timestamp: string | null;
  evidence_ref: string | null;
  data_status: MuseDataStatus;
  confidence: "HIGH" | "MEDIUM" | "LOW";
  human_verification_required: boolean;
  notes: string | null;
  sort_order: number;
  as_of: string;
}
