/**
 * Row shapes for the Muse read views.
 *
 * Hand-written on purpose: `src/integrations/supabase/types.ts` is generated by
 * Lovable and would drop these on its next regeneration. Keep this file in sync
 * with supabase/migrations/20260925120000_muse_executive_layer.sql and
 * supabase/migrations/20260927120000_muse_mission_board.sql.
 */

export type MuseDataStatus =
  | "KNOWN"
  | "AVAILABLE_NOT_CONNECTED"
  | "SOURCE_EXISTS_ACCESS_NEEDED"
  | "NOT_MEASURED"
  | "UNKNOWN"
  | "NEEDS_VERIFICATION";

export type MuseClassification =
  | "FENDI_DECISION"
  | "MUSE_ANALYSIS"
  | "DELEGATE_TO_AGENT"
  | "AUTOMATED_SYSTEM"
  | "HUMAN_OWNER"
  | "WAITING";

export type MuseVerificationState =
  | "CLAIMED"
  | "ARTIFACT_VERIFIED"
  | "SYSTEM_VERIFIED"
  | "LIVE_VERIFIED";

export type MuseSystemStatus =
  | "HEALTHY"
  | "FAILING"
  | "STALE"
  | "NEVER_RAN"
  | "NOT_OBSERVED"
  | "DISABLED"
  | "UNKNOWN";

export type MuseBriefSection =
  | "priorities"
  | "decisions_required"
  | "blockers"
  | "waiting"
  | "financial"
  | "system_failures"
  | "opportunities"
  | "commitments";

export interface MuseBriefRow {
  section: MuseBriefSection;
  rank: number;
  item_type: "open_loop" | "decision" | "system" | "task" | "improvement";
  item_id: string;
  title: string;
  domain_key: string;
  domain_name: string;
  detail: string | null;
  classification: MuseClassification;
  owner: string | null;
  due_at: string | null;
  source: string | null;
  source_ref: string | null;
  data_status: MuseDataStatus;
  verification_state: MuseVerificationState;
  as_of: string;
}

export interface MusePortfolioRow {
  domain_key: string;
  name: string;
  owner: string;
  status: string;
  systems: string[] | null;
  source_of_truth: string | null;
  current_bottleneck: string | null;
  current_initiative: string | null;
  next_review_at: string | null;
  data_status: MuseDataStatus;
  notes: string | null;
  sort_order: number;
  open_loops: number;
  blocked_loops: number;
  decisions_pending: number;
  open_conflicts: number;
  active_improvements: number;
  unhealthy_systems: number;
  primary_kpi_name: string | null;
  primary_kpi_value: number | null;
  primary_kpi_unit: string | null;
  primary_kpi_status: MuseDataStatus | null;
  primary_kpi_at: string | null;
  sources_last_verified_at: string | null;
  as_of: string;
  last_improvement_at: string | null;
  improvements_30d: number;
  active_experiments: number;
  open_tasks: number;
  active_missions: number;
  attention_flag: MuseAttentionFlag;
}

export interface MuseOpenLoopRow {
  id: string;
  domain_key: string;
  domain_name: string;
  title: string;
  owner: string | null;
  classification: MuseClassification;
  category: string;
  priority: "P0" | "P1" | "P2" | "P3";
  dependency: string | null;
  source: string;
  source_ref: string | null;
  last_evidence_at: string | null;
  next_action: string | null;
  review_at: string | null;
  resolved_at: string | null;
  verification_state: MuseVerificationState;
  notes: string | null;
  state: "OPEN" | "IN_PROGRESS" | "WAITING" | "BLOCKED" | "RESOLVED" | "CANCELLED";
  stored_state: string;
  derive_resolution_from: string | null;
  derived_system_status: MuseSystemStatus | null;
  evidence_stale: boolean;
  review_overdue: boolean;
  data_status: MuseDataStatus;
  as_of: string;
}

export interface MuseDecisionRow {
  id: string;
  domain_key: string;
  domain_name: string;
  question: string;
  context: string | null;
  evidence: string[] | null;
  options: Array<{ option?: string; pro?: string; con?: string }> | null;
  owner: string;
  classification: MuseClassification;
  status: string;
  decision_required_by: string | null;
  review_at: string | null;
  source: string;
  source_ref: string | null;
  overdue: boolean;
  days_remaining: number | null;
  created_at: string;
  as_of: string;
}

export interface MuseSystemHealthRow {
  system_key: string;
  name: string;
  role: string;
  domain_key: string | null;
  expected_cadence: string;
  cadence_minutes: number | null;
  classification: MuseClassification;
  last_success_at: string | null;
  last_failure_at: string | null;
  last_failure_detail: string | null;
  latest_activity_at: string | null;
  pending_count: number;
  failing_count: number;
  waits_on_human: boolean;
  status: MuseSystemStatus;
  data_status: MuseDataStatus;
  blocker: string | null;
  downstream_impact: string | null;
  probe_key: string | null;
  notes: string | null;
  sort_order: number;
  as_of: string;
}

export interface MuseSourceAuthorityRow {
  id: string;
  domain_key: string;
  domain_name: string;
  subject: string;
  authoritative_system: string;
  secondary_system: string | null;
  access_status: MuseDataStatus;
  freshness_target_minutes: number | null;
  last_verified_at: string | null;
  confidence: "HIGH" | "MEDIUM" | "LOW";
  known_conflict: boolean;
  reference: string | null;
  notes: string | null;
  minutes_since_verified: number | null;
  freshness: "FRESH" | "STALE" | "NEVER_VERIFIED" | "NO_TARGET";
  human_verification_required: boolean;
  open_conflicts: number;
  as_of: string;
}

export interface MuseConflictRow {
  id: string;
  domain_key: string;
  domain_name: string;
  subject: string;
  system_a: string;
  value_a: string;
  reference_a: string | null;
  system_b: string;
  value_b: string;
  reference_b: string | null;
  candidate_authority: string | null;
  status: string;
  detected_at: string;
  resolution_notes: string | null;
  as_of: string;
}

export type MuseAttentionFlag = "ATTENDED" | "UNDER_ATTENDED" | "QUIET" | "INSUFFICIENT_HISTORY";

export type MuseImprovementStatus =
  | "PROPOSED"
  | "SELECTED"
  | "IN_EXECUTION"
  | "VERIFICATION"
  | "MEASURING"
  | "DECIDED"
  | "CLOSED"
  | "REJECTED";

export type MuseVerdict = "PENDING" | "KEEP" | "REVISE" | "REVERSE" | "INCONCLUSIVE";

export type MuseTaskState =
  | "ASSIGNED"
  | "IN_PROGRESS"
  | "WAITING"
  | "BLOCKED"
  | "IMPLEMENTED"
  | "VERIFICATION"
  | "COMPLETE"
  | "CANCELLED";

export type MuseOwnerAttention = "NONE" | "INFORM" | "APPROVAL" | "DECISION" | "DIRECT_INVOLVEMENT";

export type MuseLevel = "HIGH" | "MEDIUM" | "LOW";

export interface MuseImprovementRow {
  id: string;
  domain_key: string;
  domain_name: string;
  baseline: string | null;
  problem: string;
  intervention: string;
  metric: string;
  expected_result: string | null;
  actual_result: string | null;
  owner: string;
  started_at: string | null;
  review_at: string | null;
  verdict: MuseVerdict;
  status: MuseImprovementStatus;
  verification_state: MuseVerificationState;
  source_ref: string | null;
  notes: string | null;
  review_due: boolean;
  awaiting_measurement: boolean;
  data_status: MuseDataStatus;
  created_at: string;
  as_of: string;
  // v2 — daily improvement engine
  kind: "INTERVENTION" | "OBSERVE";
  improvement_date: string | null;
  is_primary: boolean;
  function_area: string | null;
  observation: string | null;
  hypothesis: string | null;
  metric_key: string | null;
  metric_norm: string;
  confidence: MuseLevel | null;
  risk: MuseLevel | null;
  reversibility: "REVERSIBLE" | "PARTIALLY_REVERSIBLE" | "IRREVERSIBLE" | null;
  priority: "P0" | "P1" | "P2" | "P3";
  recommended_executor: string | null;
  selected_by: string | null;
  selected_at: string | null;
  linked_mission_id: string | null;
  mission_title: string | null;
  linked_experiment_id: string | null;
  definition_of_done: string[];
  verification_requirement: MuseVerificationState;
  verification_met: boolean;
  owner_attention: MuseOwnerAttention;
  awaiting_owner: boolean;
  approved_by: string | null;
  approved_at: string | null;
  implemented_at: string | null;
  measurement_window_days: number | null;
  next_iteration: string | null;
  collision_override: string | null;
  is_active_experiment: boolean;
  open_tasks: number;
  blocked_tasks: number;
  completed_tasks: number;
  execution_state:
    | "BLOCKED"
    | "WAITING"
    | "AWAITING_VERIFICATION"
    | "IN_PROGRESS"
    | "TASKS_COMPLETE"
    | "NO_TASKS";
  collision_count: number;
  collision_with: string | null;
  same_function_open_tasks: number;
  metric_data_status: MuseDataStatus | null;
  created_by: string | null;
  updated_by: string | null;
  updated_at: string;
}

export interface MuseMissionRow {
  id: string;
  domain_key: string;
  domain_name: string;
  title: string;
  objective: string;
  business_outcome: string | null;
  owner: string;
  executive_sponsor: string;
  priority: "P0" | "P1" | "P2" | "P3";
  status: "PROPOSED" | "ACTIVE" | "PAUSED" | "ACHIEVED" | "ABANDONED";
  metric: string;
  metric_key: string | null;
  baseline: string | null;
  target: string | null;
  current_value: number | null;
  current_unit: string | null;
  current_value_at: string | null;
  start_date: string | null;
  review_date: string | null;
  review_overdue: boolean;
  dependencies: string[];
  source_ref: string | null;
  evidence: string[];
  owner_attention: MuseOwnerAttention;
  created_by: string;
  updated_by: string | null;
  notes: string | null;
  improvements_total: number;
  improvements_active: number;
  improvements_kept: number;
  improvements_reversed: number;
  open_tasks: number;
  data_status: MuseDataStatus;
  human_verification_required: boolean;
  created_at: string;
  updated_at: string;
  as_of: string;
}

export interface MuseAgentTaskRow {
  id: string;
  improvement_id: string;
  improvement_title: string;
  improvement_status: MuseImprovementStatus;
  improvement_date: string | null;
  domain_key: string;
  domain_name: string;
  function_area: string | null;
  title: string;
  executor: string;
  executor_name: string | null;
  assigned_by: string;
  objective: string | null;
  instructions: string | null;
  expected_artifact: string | null;
  definition_of_done: string[];
  priority: string | null;
  priority_rank: number;
  due_at: string | null;
  state: MuseTaskState;
  blocker: string | null;
  evidence: unknown[];
  claimed_completion: string | null;
  claimed_at: string | null;
  verification_requirement: MuseVerificationState | null;
  verification_id: string | null;
  verification_state: MuseVerificationState | null;
  verified_by: string | null;
  verification_failed: boolean;
  verification_failure_reason: string | null;
  completed_at: string | null;
  cancelled_reason: string | null;
  is_open: boolean;
  is_overdue: boolean;
  data_status: MuseDataStatus;
  updated_by: string | null;
  created_at: string;
  updated_at: string;
  as_of: string;
}

export interface MuseVerificationQueueRow {
  id: string;
  subject_type: string;
  subject_ref: string;
  subject_title: string;
  executor: string | null;
  task_state: MuseTaskState | null;
  improvement_id: string | null;
  domain_key: string | null;
  claim: string;
  claimant: string | null;
  claimed_at: string;
  verification_state: MuseVerificationState;
  required_state: MuseVerificationState;
  meets_requirement: boolean;
  artifact_ref: string | null;
  repo: string | null;
  branch: string | null;
  commit_sha: string | null;
  evidence_url: string | null;
  system_evidence: string | null;
  live_evidence: string | null;
  verifier: string | null;
  verified_at: string | null;
  failure_reason: string | null;
  failed_at: string | null;
  queue_state: "PENDING" | "PASSED" | "FAILED";
  data_status: MuseDataStatus;
  human_verification_required: boolean;
  notes: string | null;
  as_of: string;
}

export interface MuseImpactRow {
  id: string;
  domain_key: string;
  domain_name: string;
  function_area: string | null;
  intervention: string;
  metric: string;
  metric_key: string | null;
  baseline: string | null;
  baseline_value: number | null;
  implemented_at: string | null;
  immediate_value: number | null;
  d7_value: number | null;
  d30_value: number | null;
  latest_value: number | null;
  latest_result: string | null;
  metric_delta: number | null;
  financial_impact_usd: number | null;
  time_saved_minutes: number | null;
  unintended_consequences: string | null;
  expected_result: string | null;
  actual_result: string | null;
  verdict: MuseVerdict;
  status: MuseImprovementStatus;
  next_iteration: string | null;
  review_at: string | null;
  measurement_count: number;
  last_measured_at: string | null;
  d7_due: boolean;
  d30_due: boolean;
  data_status: MuseDataStatus;
  human_verification_required: boolean;
  created_at: string;
  as_of: string;
}

export interface MuseKpiRow {
  metric_key: string;
  domain_key: string;
  domain_name: string;
  name: string;
  unit: string;
  direction: "UP_IS_GOOD" | "DOWN_IS_GOOD" | "NEUTRAL";
  source_system: string;
  target: string | null;
  is_primary: boolean;
  value: number | null;
  data_timestamp: string | null;
  evidence_ref: string | null;
  data_status: MuseDataStatus;
  confidence: "HIGH" | "MEDIUM" | "LOW";
  human_verification_required: boolean;
  notes: string | null;
  sort_order: number;
  as_of: string;
}
